### ISSUE TITLE
Parsing issue (getting extra two spaces before <?xml ..?>

### ISSUE THREAD

**Issue by amjo** [smarek/Croogo-Sitemap-2.0#6]
Hello there, 

first off, nice plugin, easy to use, straight forward, and i love the fact that it's not DB driven. 

however, no matter what, when generating the xml page, i get the below error:

```
XML Parsing Error: XML or text declaration not at start of entity
Location: http://maces.mosandbox.com/sitemap.xml
Line Number 1, Column 3:  <?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
--^
```

![capture](https://cloud.githubusercontent.com/assets/441767/5606660/a5bd00b8-9441-11e4-9b59-250f0cbb566e.PNG)

so yea, it's adding two extra spaces before it. i have no clue why, and i can't find anything. i've made sure all my layouts don't have extra spaces :/

thanks again, tho :+1:

**Comment by smarek** [comment]
From to me unknown reason, there are spaces before the `<?xml` document start.
Have you done some formatting to the plugin sources?

**Comment by smarek** [comment]
From what I can see, the files in this repository don't contain additional spaces. 
Check these files:
https://github.com/smarek/Croogo-Sitemap-2.0/blob/master/View/Sitemap/xml.ctp
https://github.com/smarek/Croogo-Sitemap-2.0/blob/master/View/Sitemap/xml/index.ctp
https://github.com/smarek/Croogo-Sitemap-2.0/blob/master/View/Layouts/xml/default.ctp

**Comment by amjo** [comment]
Correct, none of the plugin files have extra spaces. and no i didn't touch the plugin source files (especially the view files); tho i did edit the index() action to include other Models in the Sitemap when being rendered. 

beyond this point i believe this is not an issue with your plugin, but an issue with one of my Layouts from croogo (1.5.8). i am so sorry to cause this panic, but i thought it would be common among some people. But thank you anyway for your help :)

**Comment by smarek** [comment]
Thank you for heads up. In fact, I almost forgot about this plugin, as I wrote it really long ago. Great to see people are still using it :-)
